### Gerekli kütüphaneleri yüklemek ve fonksiyonları tanımlamak için başlamadan önce bu hücreyi çalıştırın.

In [1]:
import numpy as np
import pandas as pd
from sklearn import model_selection as ms
import sklearn.metrics

### Veri setini Pandas ile açın, '?' olan hücreleri NaN olarak tanımlamanız gerekiyor. (read_csv metodunda mevcut)

In [2]:
df = pd.read_csv('chronic_kidney_disease.csv',na_values="?")
df.head(5)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd

### Veri setindeki nümerik ve kategorik kolonları liste olarak yazın. Kategorik, nümerik ve hedef DataFramelerini oluşturun.

In [3]:


col_num = ['age', 'bp','bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc'] #liste
col_tar = 'class' #string
col_cat =['al','sg' ,'su', 'rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane'] #liste

df_num = df[col_num]
df_cat = df[col_cat]
y = df[col_tar]

### Nümerik DataFrame'deki (varsa) kayıp verileri her bir kolon için o kolonun ortalama değeri ile doldurun. DataFrame'deki her bir kolonu kendi içinde min-max şeklinde normalize edin.

In [4]:
df_num_nans=df_num.columns[df_num.isna().sum()>0]
for i in df_num_nans:
    value=df_num[i].mean()
    df_num[i].fillna(value,inplace=True,axis=0)
df_num.head(3)

C:\Users\dogan\AppData\Local\Continuum\anaconda2\envs\python37\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,48.0,80.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000
1,7.0,50.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435
2,62.0,80.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435

In [5]:
for i in df_num.columns:
    a=df_num[i]-df_num[i].min()
    b=df_num[i].max()-df_num[i].min()
    df_num[i]=a/b
df_num

C:\Users\dogan\AppData\Local\Continuum\anaconda2\envs\python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,0.522727,0.230769,0.211538,0.088575,0.010582,0.839298,0.047803,0.836735,0.777778,0.231405,0.525424
1,0.056818,0.000000,0.269309,0.042362,0.005291,0.839298,0.047803,0.557823,0.644444,0.157025,0.441938
2,0.681818,0.230769,0.856838,0.132221,0.018519,0.839298,0.047803,0.442177,0.488889,0.219008,0.441938
3,0.522727,0.153846,0.202991,0.139923,0.044974,0.671924,0.000000,0.551020,0.511111,0.185950,0.305085
4,0.556818,0.230769,0.179487,0.062901,0.013228,0.839298,0.047803,0.578231,0.577778,0.210744,0.423729
...,...,...,...,...,...,...,...,...,...,...,...
395,0.602273,0.230769,0.252137,0.121951,0.001323,0.917981,0.053933,0.857143,0.844444,0.185950,0.474576
396,0.454545,0.153846,0.113248,0.075738,0.010582,0.861199,0.022472,0.911565,1.000000,0.231405,0.694915
397,0.113636,0.230769,0.166667,0.062901,0.002646,0.835962,0.042697,0.863946,0.888889,0.181818,0.559322
398,0.170455,0.076923,0.196581,0.124519,0.007937,0.823344,0.053933,0.755102,0.933333,0.206612,0.644068
399,0.636364,0.230769,0.232906,0.042362,0.009259,0.861199,0.022472,0.863946,0.977778,0.190083,0.677966

In [6]:
df_num.describe()

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,0.562311,0.203608,0.269309,0.143583,0.035350,0.839298,0.047803,0.641254,0.664100,0.256451,0.441938
std,0.192897,0.103664,0.159792,0.126536,0.074305,0.058071,0.063366,0.184774,0.181135,0.104265,0.142426
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.454545,0.153846,0.168803,0.065469,0.006614,0.823344,0.033708,0.528912,0.555556,0.197314,0.406780
50%,0.590909,0.217189,0.222222,0.109114,0.013228,0.839298,0.047803,0.641254,0.664100,0.256451,0.441938
75%,0.704545,0.230769,0.273504,0.154685,0.035350,0.861199,0.051685,0.784014,0.777778,0.297521,0.508475
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### Kategorik DataFrame'deki (varsa) kayıp verileri her bir kolon için o kolonda en sık tekrar eden değer ile doldurun.

In [7]:
df_cat_nans=df_cat.columns[df_cat.isna().sum()>0]
for i in df_cat_nans:
    value=df_cat[i].value_counts().keys()[0]
    df_cat[i].fillna(value,inplace=True,axis=0)

C:\Users\dogan\AppData\Local\Continuum\anaconda2\envs\python37\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

### Kategorik DataFrame'deki kolonlara encoding uygulayın. Burada istediğiniz yöntemi uygulayabilirsiniz. yes/no gibi olan değerleri 1/0 olarak replace edebilir; gerekenlere one-hot encoding uygulayabilirsiniz. Veya hepsine one-hot encoding uygulayabilirsiniz. Size kalmış... Eğer one-hot uyguluyorsanız sonrasında one-hot ile değiştirdiğiniz eski kolonları düşürmeniz/kaldırmanız gerekiyor. Yani hiç text kalmamalı

In [10]:
df_test=pd.DataFrame()
for i in df_cat_nans:
    df_test= pd.get_dummies(df_cat[i],prefix=i)
    df_cat= pd.concat([df_cat,df_test],axis=1)
    df_cat.drop(columns=i,inplace=True,axis=1)

KeyError: 'al'

In [970]:
df_cat.columns

Index(['al_0.0', 'al_1.0', 'al_2.0', 'al_3.0', 'al_4.0', 'al_5.0', 'sg_1.005',
       'sg_1.01', 'sg_1.015', 'sg_1.02', 'sg_1.025', 'su_0.0', 'su_1.0',
       'su_2.0', 'su_3.0', 'su_4.0', 'su_5.0', 'rbc_abnormal', 'rbc_normal',
       'pc_abnormal', 'pc_normal', 'pcc_notpresent', 'pcc_present',
       'ba_notpresent', 'ba_present', 'htn_no', 'htn_yes', 'dm_ yes', 'dm_no',
       'dm_yes', 'cad_no', 'cad_yes', 'appet_good', 'appet_poor', 'pe_no',
       'pe_yes', 'ane_no', 'ane_yes'],
      dtype='object')

### Nümerik ve Katagorik DataFrameleri axis=1 ile birleştirip feature (X) DataFrame'ini oluşturun.

In [971]:
X=pd.concat([df_num,df_cat],axis=1)

print(X.isna().sum().sum()) # 0 olmalıdır.

0

### y'deki değerleri notckd:0 , ckd:1 olacak şekilde replace edin.

In [972]:
y=y.replace({ 'notckd' :0 , 'ckd' :1})

print(y) #sadece 0 ve 1 olmalıdır.

0      1
1      1
2      1
3      1
4      1
      ..
395    0
396    0
397    0
398    0
399    0
Name: class, Length: 400, dtype: int64

### X ve y'ye test oranı %30 olacak şekilde train-test split uygulayın.
### X_train, X_test, y_train, y_test verilerini oluşturun.

In [973]:
X_train, X_test, y_train, y_test=ms.train_test_split(X,y,test_size=0.3)
#,shuffle=False

In [974]:
X_train

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,...,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes
309,0.556818,0.076923,0.228632,0.060334,0.010582,0.848580,0.056180,0.959184,0.688889,0.243802,...,1,0,1,0,1,0,1,0,1,0
391,0.386364,0.230769,0.134615,0.037227,0.009259,0.867508,0.035955,0.850340,0.777778,0.148760,...,1,0,1,0,1,0,1,0,1,0
260,0.318182,0.230769,0.232906,0.093710,0.007937,0.899054,0.029213,0.748299,0.800000,0.297521,...,1,0,1,0,1,0,1,0,1,0
153,0.602273,0.307692,0.536325,0.599487,0.182540,0.804416,0.020225,0.353741,0.288889,0.512397,...,0,1,1,0,0,1,0,1,0,1
30,0.562311,0.153846,0.151709,0.394095,0.091270,0.804416,0.053933,0.641254,0.664100,0.256451,...,0,0,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,0.477273,0.153846,0.149573,0.098845,0.006614,0.861199,0.053933,0.741497,0.955556,0.219008,...,1,0,1,0,1,0,1,0,1,0
296,0.443182,0.153846,0.220085,0.093710,0.002646,0.854890,0.056180,0.931973,0.711111,0.169421,...,1,0,1,0,1,0,1,0,1,0
384,0.625000,0.076923,0.235043,0.042362,0.009259,0.917981,0.049438,0.836735,0.733333,0.363636,...,1,0,1,0,1,0,1,0,1,0
160,0.897727,0.076923,0.269231,0.096277,0.022487,0.899054,0.038202,0.530612,0.577778,0.297521,...,0,1,0,1,0,1,0,1,1,0
277,0.500000,0.076923,0.215812,0.114249,0.007937,0.823344,0.056180,0.857143,0.911111,0.169421,...,1,0,1,0,1,0,1,0,1,0

### Aşağıda Gaussian Naive Bayes ile predict yapan ve sonuçları çıkartan bir fonksiyon tanımlanmıştır.
### Bu fonksiyonun çıktılarına confusion matrix ekleyiniz. Çıktılar şu şekilde olmalıdır:
`(y_true,y_pred,y_proba,conf_mat)`

In [975]:
from sklearn.naive_bayes import GaussianNB

def predict_gnb(X_train,X_test,y_train,y_test):
    
    clf = GaussianNB()
    clf.fit(X_train,y_train)
    
    y_proba = clf.predict_proba(X_test)
    y_pred = clf.predict(X_test)
    
    y_true = y_test
    
    conf_mat=sklearn.metrics.confusion_matrix(y_true,y_pred);
    
    return (y_true,y_pred,y_proba,conf_mat)

### Yukarıda modifiye ettiğiniz fonksiyonun aynısını(confusion matrix ile birlikte) Decision Tree için hazırlayın:

In [976]:
from sklearn import tree

def predict_dt(X_train,X_test,y_train,y_test):
    clf = tree.DecisionTreeClassifier()
    clf.fit(X_train,y_train)
    
    y_proba = clf.predict_proba(X_test)
    y_pred = clf.predict(X_test)
    
    y_true = y_test
    
    conf_mat=sklearn.metrics.confusion_matrix(y_true,y_pred);
    
    return (y_true,y_pred,y_proba,conf_mat)

### Yukarıda modifiye ettiğiniz fonksiyonun aynısını(confusion matrix ile birlikte) KNN için hazırlayın:

In [977]:
from sklearn.neighbors import KNeighborsClassifier


def predict_knn(X_train,X_test,y_train,y_test,k=5):
    
    clf = KNeighborsClassifier(n_neighbors=k)
    clf.fit(X_train,y_train)
    
    y_proba = clf.predict_proba(X_test)
    y_pred = clf.predict(X_test)
    
    y_true = y_test
    
    conf_mat=sklearn.metrics.confusion_matrix(y_true,y_pred);

    return (y_true,y_pred,y_proba,conf_mat)

### Yukarıda modifiye ettiğiniz fonksiyonun aynısını(confusion matrix ile birlikte) SVM için hazırlayın:
*sklearn.svm.SVC varsayılan ayarlarında class probabilities'i çıkartmıyor (clf.predict_proba çalışmıyor.)*

*Bunu etkinleştirmek için tanımlarken attributeları arasında probability'yi True yapmak gerekiyor.*

In [978]:
#sklearn.svm.SVC
from sklearn.svm import SVC

def predict_svm(X_train,X_test,y_train,y_test,kernel='linear',prob=True):
    clf = SVC(kernel=kernel,probability=prob)
    clf.fit(X_train,y_train)
    
    y_proba = clf.predict_proba(X_test)
    y_pred = clf.predict(X_test)
    
    y_true = y_test
    
    conf_mat=sklearn.metrics.confusion_matrix(y_true,y_pred);

    
    if prob:
        y_proba = clf.predict_proba(X_test)
        return (y_true,y_pred,y_proba,conf_mat)
    else:
        return (y_true,y_pred,conf_mat)

In [979]:
print("accuracy: %.4f precision: %.4f tpr: %.4f fpr: %.4f"%(performance_metrics(cm_svm)))

accuracy: 0.7667 precision: 0.5821 tpr: 1.0000 fpr: 0.3457

### Ödev1'deki confusion matrix'den performans metriklerini çıkartan fonksiyonunuzu yapıştırın.

In [980]:
def performance_metrics(cm):
    [[tp,fn],[fp,tn]]=cm
    accuracy=(tp+tn)/(tp+tn+fp+fn)
    precision=tp/(tp+fp)
    tpr=tp/(tp+fn)
    fpr=fp/(fp+tn)
    
    return accuracy, precision, tpr, fpr

### Her bir classifier için confusion matrixleri oluşturarak performance_metrics fonksiyonuyla sonuçları yazdırın.
### KNN için K = 1,3,5,7 değerlerini ayrı ayrı deneyin.
### SVM için ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’ kernellerini ayrı ayrı deneyin.
#### * Her bir classifier için sonuçları ekrana yazdırmadan önce classifier'ın adını da yazdırın.

In [981]:
cm_svm=predict_svm(X_train,X_test,y_train,y_test,kernel='linear',prob=True)[-1]
cm_knn=predict_knn(X_train,X_test,y_train,y_test,k=5)[-1]
cm_dt=predict_dt(X_train,X_test,y_train,y_test)[-1]
cm_gnb=predict_gnb(X_train,X_test,y_train,y_test)[-1]

print("SVM:")
for i in ["poly", "rbf", "sigmoid"]:
    cm_svm=predict_svm(X_train,X_test,y_train,y_test,kernel=i,prob=True)[-1]
    print(i,": ",("accuracy: %.4f precision: %.4f tpr: %.4f fpr: %.4f"%(performance_metrics(cm_svm))))
    
print("\nKNN:")
for i in [1,3,5,7]:
    cm_knn=predict_knn(X_train,X_test,y_train,y_test,k=i)[-1]
    print(i,": ",("accuracy: %.4f precision: %.4f tpr: %.4f fpr: %.4f"%(performance_metrics(cm_knn))))
    
print("\nDecTree:")
cm_dt=predict_dt(X_train,X_test,y_train,y_test)[-1]
print("accuracy: %.4f precision: %.4f tpr: %.4f fpr: %.4f"%(performance_metrics(cm_dt)))

print("\nGausNaive:")
cm_gnb=predict_gnb(X_train,X_test,y_train,y_test)[-1]
print("accuracy: %.4f precision: %.4f tpr: %.4f fpr: %.4f"%(performance_metrics(cm_gnb)))

SVM:
poly :  accuracy: 0.9750 precision: 0.9492 tpr: 1.0000 fpr: 0.0469
rbf :  accuracy: 0.9750 precision: 0.9492 tpr: 1.0000 fpr: 0.0469
sigmoid :  accuracy: 0.8917 precision: 0.8116 tpr: 1.0000 fpr: 0.2031

KNN:
1 :  accuracy: 0.9667 precision: 0.9333 tpr: 1.0000 fpr: 0.0625
3 :  accuracy: 0.9583 precision: 0.9180 tpr: 1.0000 fpr: 0.0781
5 :  accuracy: 0.9500 precision: 0.9032 tpr: 1.0000 fpr: 0.0938
7 :  accuracy: 0.9500 precision: 0.9032 tpr: 1.0000 fpr: 0.0938

DecTree:
accuracy: 0.9333 precision: 0.9615 tpr: 0.8929 fpr: 0.0312

GausNaive:
accuracy: 0.9750 precision: 0.9492 tpr: 1.0000 fpr: 0.0469

In [ ]:
SVM:
poly :  accuracy: 0.9667 precision: 0.9130 tpr: 1.0000 fpr: 0.0513
rbf :  accuracy: 0.9583 precision: 0.8936 tpr: 1.0000 fpr: 0.0641
sigmoid :  accuracy: 0.8167 precision: 0.6562 tpr: 1.0000 fpr: 0.2821

KNN:
1 :  accuracy: 0.9667 precision: 0.9130 tpr: 1.0000 fpr: 0.0513
3 :  accuracy: 0.9500 precision: 0.8750 tpr: 1.0000 fpr: 0.0769
5 :  accuracy: 0.9417 precision: 0.8571 tpr: 1.0000 fpr: 0.0897
7 :  accuracy: 0.9250 precision: 0.8235 tpr: 1.0000 fpr: 0.1154

DecTree:
accuracy: 0.9667 precision: 0.9524 tpr: 0.9524 fpr: 0.0256

GausNaive:
accuracy: 0.9750 precision: 0.9333 tpr: 1.0000 fpr: 0.0385

### Çıkan sonuçlara göre en iyi sonuç veren classifier'ı ve özelliğini belirleyin (KNN ise k, SVM ise kernel gibi)
### Bu adımdan sonra bu classifier'ı bu özelliklerle kullanacaksınız.

In [801]:
from sklearn.decomposition import PCA

pca=PCA()

### Bu adımda X DataFrame'inize(features) PCA dönüşümü uygulayın ve PCA_X DataFrame'ini elde edin.

In [802]:
x_pca= pca.fit_transform(X) 
PCA_X = pd.DataFrame(x_pca)
#PCA_X.iloc[:,0:3]
PCA_X[[0,1,2]]

            0         1         2
0    0.500039 -1.042149 -0.535571
1   -0.729405  0.170628  0.223221
2    1.106002  0.007854 -0.317376
3    1.836745  0.922687  1.567287
4   -0.424671  0.719563 -0.461326
..        ...       ...       ...
395 -1.110301 -0.220816  0.277899
396 -1.195138  0.280409 -0.208031
397 -1.159311 -0.187177  0.305967
398 -1.175101  0.295965 -0.189138
399 -1.167657  0.264283 -0.226350

[400 rows x 3 columns]

### PCA dönüşümünde hangi kolonun ne kadar bilgi taşıdığını yazdırın. (explained variance ratio)

In [803]:
pca.explained_variance_ratio_

array([2.90535377e-01, 1.02236322e-01, 7.22351587e-02, 5.88713216e-02,
       5.42263556e-02, 4.70297163e-02, 4.25813007e-02, 4.10272611e-02,
       3.60714233e-02, 3.52484889e-02, 3.09675833e-02, 2.52600547e-02,
       2.30947751e-02, 2.12167797e-02, 2.00013105e-02, 1.90940187e-02,
       1.57932261e-02, 1.10890157e-02, 8.53346165e-03, 7.18658293e-03,
       6.55679975e-03, 5.52144060e-03, 5.07976147e-03, 3.99152465e-03,
       3.01072657e-03, 2.47808826e-03, 2.03262389e-03, 1.83505953e-03,
       1.64124021e-03, 1.46536853e-03, 1.00437754e-03, 9.86428301e-04,
       7.88462523e-04, 6.11321129e-04, 4.53450397e-04, 2.43793200e-04,
       5.72980001e-32, 1.14211116e-32, 3.62752093e-33, 2.35420649e-33,
       2.08357103e-33, 2.08357103e-33, 2.08357103e-33, 2.08357103e-33,
       2.08357103e-33, 2.08357103e-33, 2.08357103e-33, 2.08357103e-33,
       1.02525603e-33])

### Bilginin en az %90'ını kapsayacak şekilde ilk birkaç kolonu seçin ve X_necessary DataFrame'ini oluşturun.

In [804]:
pca.explained_variance_ratio_ [0:15].sum()

X_necessary = pd.DataFrame(PCA_X[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]])
X_necessary[0]

0      0.500039
1     -0.729405
2      1.106002
3      1.836745
4     -0.424671
         ...
395   -1.110301
396   -1.195138
397   -1.159311
398   -1.175101
399   -1.167657
Name: 0, Length: 400, dtype: float64

In [805]:
len( "34  50  55  56  73  99 105 107 118 145 156 160 168 169 180 189 195 199\
 203 205 226 238 243 245 247 259 267 275 286 287 295 302 317 327 343 346\
 356 367 388 398".split())

40

### n=10 olacak şekilde X_necessary ve y'ye n-Fold Cross Validation (shuffle ile birlikte) uygulayarak
### X_trains, X_tests, y_trains, y_tests listelerini oluşturun.

In [806]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=10, shuffle=True, random_state=True)
X_trains=[]
X_tests=[]
y_trains=[]
y_tests=[]

for train_index, test_index in kfold.split(X_necessary):
    X_trains.append(X_necessary.iloc[train_index])
    X_tests.append(X_necessary.iloc[test_index])
    y_trains.append(y.iloc[train_index])
    y_tests.append(y.iloc[test_index])

### Bu adımda şu iterasyonu yaparak X_trains, X_tests, y_trains, y_tests listelerindeki her bir eleman için
### performans metriklerini hesaplamanız gerekiyor: (Kod fikir vermesi için)

In [983]:

accuracies = []
n=10

for i in range(n):
    X_train = X_trains[i]
    X_test = X_tests[i]
    y_train = y_trains[i]
    y_test = y_tests[i]
    cm_knn=predict_knn(X_train,X_test,y_train,y_test,k=1)[-1] #yukarıda seçtiğiniz en iyi performans veren classifier
    accuracy=performance_metrics(cm_knn)[0]
    accuracies.append(accuracy) #accuracy

mean_acc = sum(accuracies)/len(accuracies)
print(mean_acc)

0.9974999999999999

1. En iyi performans veren classifier'ı seçerken neye göre seçtiniz? Neden?

2. En son adımda ortalama accuracy'yi hesapladık. Cross validation'daki setler için başka neleri hesaplamamız mantıklı olurdu?

3. Öğrendikleriniz / Katkılarınız

4. (Varsa) eklemek istedikleriniz

Grup Üyesi 1 İsim : Rıza Semih Koca

1. knn 1 her shuffle için 4 kategoride(accuracy,precision..)  en yüksek değeri aldığı için

2. confusion matrix

3. pandasda slice kullanımı,cross validationun kullanımı ...

4. SVM ‘precomputed’ square matrix olmalı hatası veriyor


---
Grup Üyesi 2 İsim : 

1. 

2. 

3. 

4. 


---
Grup Üyesi 3 İsim : 

1. 

2. 

3. 

4. 


---
Grup Üyesi 4 İsim : 

1. 

2. 

3. 

4. 


---
Grup Üyesi 5 İsim : 

1. 

2. 

3. 

4. 


---
Grup Üyesi 6 İsim : 

1. 

2. 

3. 

4. 


---
Grup Üyesi 7 İsim : 

1. 

2. 

3. 

4.